#!/bin/sh

echo "pre-commit..."

git remote update origin --prune

if git rev-parse --verify HEAD
then
    against=HEAD
else
    against=8f71dcf6b6e734541735249845ec875ab20e4272
fi

FILES=$(git diff-index --name-only --cached --diff-filter=ACMR $against -- )
for FILE in $FILES
do
    case ${FILE} in
    *.go )
      gofmt -s -w $FILE
      goimports -w $FILE
      golangci -w $FILE
      git add $FILE
      echo goimports $FILE
      ;;
    esac
done